### ISSUE TITLE
Update for ZF3 compatibility (zend-mvc)

### ISSUE THREAD

**Issue by adamculp** [radnan/rdn-csv#11]
This isn't installing via Composer because of the current requirement of zend-mvc version 2.* in a ZF3 app, which requires zend-mvc v3.*

**Comment by divyasreem** [comment]
Hi,

Upgrade to zf3 which is not supporting,

Please try to resolve this.

**Comment by adamculp** [comment]
I just issued a pull request that fixes this.

**Comment by divyasreem** [comment]
Upgrade to zf3 
This is my composer : 
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "require": {
        "php": ">=5.5",
        "zendframework/zendframework": "3.*",
        "zendframework/zend-mvc": "3.*",
        "zendframework/zend-mvc-i18n": "^1.0",
        "zendframework/zend-servicemanager": "^3.3"
    },
    "require-dev": {
        "zendframework/zend-component-installer": "^1.0"
    }
}
Problem 1
    - Installation request for radnan/rdn-csv ^1.1 -> satisfiable by radnan/rdn-csv[v1.1.0].
    - radnan/rdn-csv v1.1.0 requires zendframework/zend-mvc 2.* -> satisfiable by zendframework/zend-mvc[2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.11, 2.7.12, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.

**Comment by kaamzzz** [comment]
Hello,

the issue has not been corrected yet, i am facing the same error as divya.

Is there any way to contour the problem ?

thanks

**Comment by radnan** [comment]
`v2` has been released with zf3 support #12
