### ISSUE TITLE
can not initialize module

### ISSUE THREAD

**Issue by frodeco** [radnan/rdn-csv#6]
i installed with composer and added 'RdnCsv' to my application.config.php but unfortunately i get this error:
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (RdnCsv) could not be initialized.' in /usr/local/zend/var/apps/http/**default**/0/noamjewels/1.0.0_58/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:195 Stack trace: #0 /usr/local/zend/var/apps/http/**default**/0/noamjewels/1.0.0_58/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(169): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 /usr/local/zend/var/apps/http/**default**/0/noamjewels/1.0.0_58/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(96): Zend\ModuleManager\ModuleManager->loadModule('RdnCsv') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 /usr/local/zend/var/apps/http/**default**/0/noamjewels/1.0.0_58/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, in /usr/local/zend/var/apps/http/**default**/0/noamjewels/1.0.0_58/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 195

**Comment by radnan** [comment]
This seems like a very unusual problem. Could you please post your PHP version, your operating system, and what version of zend framework you are using please?
